spring:
  cloud:
    openfeign:
      client:
        config:
          restApi:
            url: http://localhost:8765/restApi
          webApiSalesAccounting:
            url: http://localhost:8765/webApiSalesAccounting
          webApiShop:
            url: http://localhost:8765/webApiShop

api:
  basic-uri:
    restApi: http://localhost:8765/restApi/
    webApiSalesAccounting: http://localhost:8765/webApiSalesAccounting/
    webApiShop: http://localhost:8765/webApiShop/

tmpVar: configServer
